#!/usr/bin/env python3
"""Grounded writing interface — mandatory schema for LLM-written sections (anti-hallucination v3).

Why this tool is needed:
- The previous anti-hallucination v2 prevented the LLM from writing bib entries, but section content was still freely generated by the LLM
- v3 introduces "grounded writing": when the LLM writes a section it must provide cite_key + verbatim quote from the source
- This tool verifies whether every claim in the LLM-output section is accompanied by a quote

New protocol for LLM-written sections (mandatory):
Each paragraph must start with the following JSON, then output LaTeX:
    {
      "claims": [
        {
          "text": "Vaswani et al. proposed the Transformer architecture",
          "cite_key": "vaswani2017attention",
          "quote": "we propose a new simple network architecture, the Transformer...",
          "quote_location": {"file": "fulltext/vaswani2017attention.txt", "char_offset": 1234}
        }
      ]
    }

Tool responsibilities:
1. Receive the JSON+LaTeX mixed output written by the LLM
2. Parse the claims list
3. For each claim, verify whether the quote actually appears in the fulltext file
4. Verify whether cite_key exists in references.bib
5. Output the verified "clean" LaTeX (strip JSON metadata)
6. Any claim missing a quote or whose quote anchoring fails → reject the output
"""

from __future__ import annotations

import argparse
import json
import re
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent))
from retrieval_log import has_provenance  # noqa: E402


# Marker for JSON block at the start of LaTeX
CLAIMS_BLOCK_RE = re.compile(r"^```json\s*\n(.*?)\n```\s*\n(.*)$", re.DOTALL)
# Also supports without ``` fences
CLAIMS_BLOCK_RE2 = re.compile(r"^\{\s*\"claims\".*?\}\s*\n(.*)$", re.DOTALL | re.MULTILINE)


def load_fulltext(cite_key: str, task_dir: Path) -> str | None:
    p = task_dir / "paper" / "fulltext" / f"{cite_key}.txt"
    if p.exists():
        return p.read_text(encoding="utf-8", errors="ignore")
    return None


def parse_grounded_output(raw_output: str) -> tuple[list[dict] | None, str]:
    """Parse the LLM-output claims JSON + LaTeX."""
    m = CLAIMS_BLOCK_RE.match(raw_output)
    if m:
        try:
            data = json.loads(m.group(1))
            return data.get("claims", []), m.group(2)
        except json.JSONDecodeError:
            return None, raw_output
    # Also allow JSON to start directly
    raw_output_stripped = raw_output.lstrip()
    if raw_output_stripped.startswith("{"):
        try:
            # Find closing }
            depth = 0
            for i, c in enumerate(raw_output_stripped):
                if c == "{":
                    depth += 1
                elif c == "}":
                    depth -= 1
                    if depth == 0:
                        json_part = raw_output_stripped[: i + 1]
                        latex_part = raw_output_stripped[i + 1:].lstrip()
                        data = json.loads(json_part)
                        return data.get("claims", []), latex_part
        except json.JSONDecodeError:
            pass
    return None, raw_output


def verify_claim(claim: dict, task_dir: Path) -> dict:
    """Verify whether a single claim is grounded."""
    cite_key = claim.get("cite_key", "")
    quote = claim.get("quote", "")
    text = claim.get("text", "")
    issues = []
    if not cite_key:
        issues.append("missing_cite_key")
    if not quote:
        issues.append("missing_quote")
    if not text:
        issues.append("missing_text")
    # Verify whether the quote actually appears in the fulltext
    if cite_key and quote:
        fulltext = load_fulltext(cite_key, task_dir)
        if not fulltext:
            issues.append(f"no_fulltext_for_cite_key:{cite_key}")
        else:
            # Normalized match: collapse extra whitespace
            quote_norm = re.sub(r"\s+", " ", quote.lower().strip())
            ft_norm = re.sub(r"\s+", " ", fulltext.lower())
            if quote_norm not in ft_norm:
                issues.append(f"quote_not_in_fulltext:{cite_key}")
    return {**claim, "issues": issues, "verified": not issues}


def verify_and_extract(raw_output: str, task_dir: Path) -> dict:
    """Main entry: verify + extract LaTeX."""
    claims, latex = parse_grounded_output(raw_output)
    if claims is None:
        return {
            "verified": False,
            "reason": "no_claims_block_found",
            "claims": [],
            "latex": raw_output,
        }
    verified_claims = [verify_claim(c, task_dir) for c in claims]
    all_ok = all(c["verified"] for c in verified_claims)
    return {
        "verified": all_ok,
        "claims": verified_claims,
        "latex": latex if all_ok else "",
        "failed_claims": [c for c in verified_claims if not c["verified"]],
    }


def main() -> None:
    parser = argparse.ArgumentParser(description="Grounded writing verification (anti-hallucination v3)")
    parser.add_argument("task_dir", type=Path)
    parser.add_argument("--input", type=Path, required=True, help="LLM output file (JSON+LaTeX mixed)")
    parser.add_argument("-o", "--output", type=Path, default=None, help="Output clean LaTeX")
    args = parser.parse_args()
    raw = args.input.read_text(encoding="utf-8")
    result = verify_and_extract(raw, args.task_dir)
    if args.output and result["verified"]:
        args.output.write_text(result["latex"] + "\n", encoding="utf-8")
    out = json.dumps({k: v for k, v in result.items() if k != "latex"}, indent=2, ensure_ascii=False)
    print(out)
    raise SystemExit(0 if result["verified"] else 1)


if __name__ == "__main__":
    main()
